// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5aSL8TxgpHI9FCHWt3faGzk4_mOjGNTo',
    appId: '1:189485304697:web:46d86999ff811a92df3da8',
    messagingSenderId: '189485304697',
    projectId: 'nossa-listinha',
    authDomain: 'nossa-listinha.firebaseapp.com',
    storageBucket: 'nossa-listinha.appspot.com',
    measurementId: 'G-47VWCZJ74H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKFTuya16GITsCiubBJn6XbqbgNiYCic8',
    appId: '1:189485304697:android:d19c304d5aadf184df3da8',
    messagingSenderId: '189485304697',
    projectId: 'nossa-listinha',
    storageBucket: 'nossa-listinha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJD5QZQgRDPQb71_N6zT_wJikaBs95lNE',
    appId: '1:189485304697:ios:3472cd7ffceaaaf9df3da8',
    messagingSenderId: '189485304697',
    projectId: 'nossa-listinha',
    storageBucket: 'nossa-listinha.appspot.com',
    iosBundleId: 'com.example.nossaListinha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJD5QZQgRDPQb71_N6zT_wJikaBs95lNE',
    appId: '1:189485304697:ios:3472cd7ffceaaaf9df3da8',
    messagingSenderId: '189485304697',
    projectId: 'nossa-listinha',
    storageBucket: 'nossa-listinha.appspot.com',
    iosBundleId: 'com.example.nossaListinha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5aSL8TxgpHI9FCHWt3faGzk4_mOjGNTo',
    appId: '1:189485304697:web:0312ec07d4ec924bdf3da8',
    messagingSenderId: '189485304697',
    projectId: 'nossa-listinha',
    authDomain: 'nossa-listinha.firebaseapp.com',
    storageBucket: 'nossa-listinha.appspot.com',
    measurementId: 'G-563ZNM01KG',
  );
}
